export const state = {
  route: "dashboard",
  marketsSub: "most_active",
  marketsCache: new Map(),
  metrics: [],
  watchlists: [],
  editingWatchlist: null,
  expandedWatchlists: new Set(),
  ticker: null,
  tickerName: null,
  tickerBackPath: null,
  tickerMainTab: "chart",
  tickerView: "income_statement",
  tickerFinancialsData: null,
  tickerFinancialsAsPercent: false,
  chartPeriod: "1mo",
  chartInterval: "1d",
  compareTickers: [],
  indicators: new Set(),
  llmOpen: false,
  llmHistory: [],
  llmStreaming: false,
  marketStatus: null,
  marketStatusTimer: null,
  chatConversations: [],
  chatActiveId: null,
  chatStreaming: false,
  chatProviders: { llama: false, claude: false, openai: false },
  chatSettingsOpen: false,
  llmWebSearch: false,
  chatWebSearch: false,
  chatDeepResearch: false,
};
