export const state = {
  route: "dashboard",
  marketsSub: "most_active",
  marketsMacroTab: "gdp",
  marketsPredictionTab: "all",
  marketsPredictionQuery: "",
  marketsPredictionSelectedEvent: null,
  marketsPredictionSelectedMarket: null,
  predictionMarketTitlesExpanded: new Set(),
  macroCache: new Map(),
  marketsCache: new Map(),
  predictionMarketsCache: new Map(),
  metrics: [],
  watchlists: [],
  editingWatchlist: null,
  expandedWatchlists: new Set(),
  ticker: null,
  tickerName: null,
  tickerBackPath: null,
  assetType: "stock",
  tickerMainTab: "chart",
  tickerView: "income_statement",
  tickerFinancialsData: null,
  tickerFinancialsAsPercent: false,
  etfHoldingsCache: new Map(),
  chartPeriod: "1mo",
  chartInterval: "1d",
  compareTickers: [],
  chartRows: [],
  chartAnalysis: null,
  chartAnalysisSelectedIndex: 0,
  chartAnalysisLoading: false,
  chartLiveQuote: null,
  chartLive: false,
  chartLivePendingStart: false,
  chartLivePrevPeriod: "1mo",
  chartLivePrevInterval: "1d",
  chartLiveTicker: null,
  chartLiveMode: null,
  chartLiveWarning: null,
  chartLiveTimer: null,
  chartLiveLookback: 60,
  tickerHeaderLive: false,
  tickerHeaderLivePending: false,
  tickerHeaderLiveMode: null,
  tickerHeaderLiveWarning: null,
  indicators: new Set(),
  llmOpen: false,
  llmHistory: [],
  llmStreaming: false,
  marketStatus: null,
  marketStatusTimer: null,
  chatConversations: [],
  chatActiveId: null,
  chatStreaming: false,
  chatContextCache: new Map(),
  chatResearchEffort: "default",
  chatProviders: { llama: false, claude: false, openai: false },
  chatSettingsOpen: false,
  llmWebSearch: false,
  chatWebSearch: false,
  chatDeepResearch: false,
};
